apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-application
    appstudio.openshift.io/component: test-application-devfile-sample-ihrj-sample
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-application-devfile-sample-ihrj-sample
  namespace: rorai-tenant
spec:
  url: https://github.com/nodeshift-starters/devfile-sample
