apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-application-devfile-sample-ihrj-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-application-devfile-sample-ihrj-sample
    app.kubernetes.io/part-of: test-application
  name: test-application-devfile-sample-ihrj-sample
  namespace: rorai-tenant
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-application-devfile-sample-ihrj-sample
    weight: 100
status: {}
